name: WeChat girlfriend greeting
on:
  schedule:
  - cron:  '09 23 * * *'
  workflow_dispatch:

jobs:
  send_message:
    runs-on: ubuntu-latest
    name: WeChat girlfriend greeting

    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: main

    - name: sender
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
    - run: pip install -r ./requirements.txt && python ./app.py

    env:
      TEMP_ID: ${{ secrets.TEMP_ID }}
      APPID: ${{ secrets.APPID }}
      APPSECRET: ${{ secrets.APPSECRET}}
      WECHAT_ID: ${{ secrets.WECHAT_ID}}
      ANNIVERSARIES: ${{ secrets.ANNIVERSARIES }}
      CUSTOM_DATE: ${{ secrets.CUSTOM_DATE}}
      CUSTOM_DATE_TIME: ${{ secrets.CUSTOM_DATE_TIME }}
      BIRTHDAY: ${{ secrets.BIRTHDAY }}
      REPID_API_KEY: ${{ secrets.REPID_API_KEY }}
      REPID_API_SECRETE: ${{ secrets.REPID_API_SECRETE}}